### NUMPY

Numpy is the core library for scientific computing in Python.


#### NUMPY VS LIST

To use numpy we need to import numpy library

In [2]:
import numpy as np

Using numpy we can create arrays of n dimension<br>
1-D Array

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a[0]

1

In [6]:
a[1]

2

Now lets check how much space does list take for the same 1-D array

In [7]:
import time
import sys

In [8]:
b=[1,2,3]
print(sys.getsizeof(3)*len(b))

84


In [9]:
print(a.size*a.itemsize)

12


So you can see that for the same list numpy takes much less bytes than the list

#### Memory occupied by list vs numpy

In [10]:
size=100000
l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

start=time.time()

result=[(x,y) for x,y in zip(l1,l2)]

print((time.time()-start)*1000)#LIST

start=time.time()

result=a1+a2

print((time.time()-start)*1000)#NUMPY

44.048309326171875
9.119272232055664


#### BASIC NUMPY OPERATIONS

In [11]:
a=np.array([5,6,7]) #1-D ARRAY
a[0]

5

In [14]:
a=np.array([[1,2],[3,4],[5,6]]) #2-D ARRAY
print(a.ndim) #CHECK DIMENSION OF ARRAY
a

2


array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a.itemsize #SIZE OF 1 ITEM IN ARRAY

4

In [16]:
a.dtype #DATA TYPE OF ARRAY

dtype('int32')

In [18]:
a.shape #SHAPE OF ARRAY

(3, 2)

In [19]:
np.arange(1,5) #creates an arrange from 1 to 4 

array([1, 2, 3, 4])

In [20]:
np.arange(1,5,2) #creates an arrange from 1 to 4 with step of 2

array([1, 3])

In [21]:
np.linspace(1,5,20) #creates an arrange from 1 to 4 taking randomly 20 numbers including all the numbers between 1 to 5

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [22]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [23]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [26]:
a.max()

6

In [27]:
a.min()

1

In [29]:
a.sum(axis=0)

array([ 9, 12])

In [30]:
a.sum(axis=1)

array([ 3,  7, 11])

In [35]:
b=np.array([[5,6],[7,8],[9,10]])

In [36]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
b

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
a+b

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [39]:
a-b

array([[-4, -4],
       [-4, -4],
       [-4, -4]])

In [40]:
a*b

array([[ 5, 12],
       [21, 32],
       [45, 60]])

In [41]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ],
       [0.55555556, 0.6       ]])

In [43]:
b=np.array([[5,6],[7,8]])

In [44]:
a.dot(b)

array([[19, 22],
       [43, 50],
       [67, 78]])

#### INDEXING AND SLICING

In [46]:
c=[2,4,6,8]

In [47]:
c[0:2]

[2, 4]

In [48]:
c[-1]

8

In [52]:
b

array([[5, 6],
       [7, 8]])

In [51]:
b[1,1]

8

In [54]:
b[0,1]

6

In [58]:
b[0:2,0]

array([5, 7])

In [61]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 6],
       [7, 8]])

In [68]:
result=np.hsplit(a,2)

In [69]:
result[0]

array([[1],
       [3],
       [5]])

In [70]:
result[1]

array([[2],
       [4],
       [6]])

In [71]:
a=np.array([1,2,4,5,12,3,5,66,33,1,9])

In [72]:
b=a>4

In [73]:
b

array([False, False, False,  True,  True, False,  True,  True,  True,
       False,  True])

In [74]:
a[b]

array([ 5, 12,  5, 66, 33,  9])

In [75]:
a[b]=-1

In [76]:
a

array([ 1,  2,  4, -1, -1,  3, -1, -1, -1,  1, -1])